// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InventoryService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GRPCDemo {
  public static partial class gRPC
  {
    static readonly string __ServiceName = "gRPCDemo.gRPC";

    static readonly grpc::Marshaller<global::GRPCDemo.DeductionRequest> __Marshaller_gRPCDemo_DeductionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCDemo.DeductionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCDemo.DeductionReply> __Marshaller_gRPCDemo_DeductionReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCDemo.DeductionReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCDemo.GetInventoryQuantityRequest> __Marshaller_gRPCDemo_GetInventoryQuantityRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCDemo.GetInventoryQuantityRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GRPCDemo.GetInventoryQuantityReply> __Marshaller_gRPCDemo_GetInventoryQuantityReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GRPCDemo.GetInventoryQuantityReply.Parser.ParseFrom);

    static readonly grpc::Method<global::GRPCDemo.DeductionRequest, global::GRPCDemo.DeductionReply> __Method_Deduction = new grpc::Method<global::GRPCDemo.DeductionRequest, global::GRPCDemo.DeductionReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Deduction",
        __Marshaller_gRPCDemo_DeductionRequest,
        __Marshaller_gRPCDemo_DeductionReply);

    static readonly grpc::Method<global::GRPCDemo.GetInventoryQuantityRequest, global::GRPCDemo.GetInventoryQuantityReply> __Method_GetInventoryQuantity = new grpc::Method<global::GRPCDemo.GetInventoryQuantityRequest, global::GRPCDemo.GetInventoryQuantityReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetInventoryQuantity",
        __Marshaller_gRPCDemo_GetInventoryQuantityRequest,
        __Marshaller_gRPCDemo_GetInventoryQuantityReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GRPCDemo.InventoryServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of gRPC</summary>
    [grpc::BindServiceMethod(typeof(gRPC), "BindService")]
    public abstract partial class gRPCBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GRPCDemo.DeductionReply> Deduction(global::GRPCDemo.DeductionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::GRPCDemo.GetInventoryQuantityReply> GetInventoryQuantity(global::GRPCDemo.GetInventoryQuantityRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for gRPC</summary>
    public partial class gRPCClient : grpc::ClientBase<gRPCClient>
    {
      /// <summary>Creates a new client for gRPC</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public gRPCClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for gRPC that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public gRPCClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected gRPCClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected gRPCClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GRPCDemo.DeductionReply Deduction(global::GRPCDemo.DeductionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Deduction(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GRPCDemo.DeductionReply Deduction(global::GRPCDemo.DeductionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Deduction, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCDemo.DeductionReply> DeductionAsync(global::GRPCDemo.DeductionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeductionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCDemo.DeductionReply> DeductionAsync(global::GRPCDemo.DeductionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Deduction, null, options, request);
      }
      public virtual global::GRPCDemo.GetInventoryQuantityReply GetInventoryQuantity(global::GRPCDemo.GetInventoryQuantityRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetInventoryQuantity(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GRPCDemo.GetInventoryQuantityReply GetInventoryQuantity(global::GRPCDemo.GetInventoryQuantityRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetInventoryQuantity, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCDemo.GetInventoryQuantityReply> GetInventoryQuantityAsync(global::GRPCDemo.GetInventoryQuantityRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetInventoryQuantityAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GRPCDemo.GetInventoryQuantityReply> GetInventoryQuantityAsync(global::GRPCDemo.GetInventoryQuantityRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetInventoryQuantity, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override gRPCClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new gRPCClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(gRPCBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Deduction, serviceImpl.Deduction)
          .AddMethod(__Method_GetInventoryQuantity, serviceImpl.GetInventoryQuantity).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, gRPCBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Deduction, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GRPCDemo.DeductionRequest, global::GRPCDemo.DeductionReply>(serviceImpl.Deduction));
      serviceBinder.AddMethod(__Method_GetInventoryQuantity, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GRPCDemo.GetInventoryQuantityRequest, global::GRPCDemo.GetInventoryQuantityReply>(serviceImpl.GetInventoryQuantity));
    }

  }
}
#endregion
